:: Currently not executed by Tron as I'm unsure if these will stall the script or not
:: If you can test these on a system with these products and let me know if it finishes
:: without interruptions or prompts, it'd be very helpful and I'll enable it for Tron


if exist "C:\Program Files (x86)\Monopoly\unins000.exe" ( start /wait "GS" "C:\Program Files (x86)\Monopoly\unins000.exe" >nul 2>&1 )
REM HP Games legacy uninstaller: Fall 2009, Regions affected: Poland, Finland, United Kingdom, Canada, Italy, Germany, Japan, France, Korea, Spain, Switzerland, Netherlands, Belgium, Norway, Brazil, 
if exist "C:\Program Files (x86)\HP Games\Bejeweled 2 Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Bejeweled 2 Deluxe\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Blasterball 2 Revolution\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Blasterball 2 Revolution\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Blasterball 3\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Blasterball 3\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Bob the Builder Can-Do-Zoo\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Bob the Builder Can-Do-Zoo\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Build-a-lot 2\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Build-a-lot 2\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Build-a-lot 3\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Build-a-lot 3\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Chocolatier - Decadence by Design\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Chocolatier - Decadence by Design\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Chuzzle Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Chuzzle Deluxe\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Dora's Carnival Adventure\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Dora's Carnival Adventure\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Eighteen Wheels of Steel Haulin'\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Eighteen Wheels of Steel Haulin'\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Farm Frenzy - Pizza Party\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Farm Frenzy - Pizza Party\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\FATE Undiscovered Realms\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\FATE Undiscovered Realms\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Jewel Quest Solitaire 2\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Jewel Quest Solitaire 2\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\John Deere Drive Green\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\John Deere Drive Green\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Liong - The Lost Amulets\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Liong - The Lost Amulets\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Mah Jong Medley\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Mah Jong Medley\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Mortimer Beckett and the Time Paradox\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Mortimer Beckett and the Time Paradox\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Mystery P.I. - The New York Fortune\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Mystery P.I. - The New York Fortune\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Mystery P.I. - The Vegas Heist\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Mystery P.I. - The Vegas Heist\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Peggle\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Peggle\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Penguins!\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Penguins!\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Polar Bowler\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Polar Bowler\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Polar Golfer\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Polar Golfer\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Slingo Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Slingo Deluxe\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Super Collapse 3\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Super Collapse 3\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\The Hidden Object Game Show\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\The Hidden Object Game Show\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Totem Tribe\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Totem Tribe\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Virtual Villagers - The Secret City\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Virtual Villagers - The Secret City\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\World of Goo\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\World of Goo\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Zuma Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Zuma Deluxe\Uninstall.exe" >nul 2>&1 )
rem HP Games legacy uninstaller: Spring 2010, Regions affected: USA
if exist "C:\Program Files (x86)\HP Games\Bejeweled 2 Deluxe\Uninstall.exe" (start /wait "GS" "C:\Program Files (x86)\HP Games\Bejeweled 2 Deluxe\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files (x86)\HP Games\Blackhawk Striker 2\Uninstall.exe" (start /wait "GS" "C:\Program Files (x86)\HP Games\Blackhawk Striker 2\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files (x86)\HP Games\Blasterball 2 Revolution\Uninstall.exe" (start /wait "GS" "C:\Program Files (x86)\HP Games\Blasterball 2 Revolution\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files (x86)\HP Games\Bob the Builder Can-Do-Zoo\Uninstall.exe" (start /wait "GS" "C:\Program Files (x86)\HP Games\Bob the Builder Can-Do-Zoo\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files (x86)\HP Games\Chuzzle Deluxe\Uninstall.exe" (start /wait "GS" "C:\Program Files (x86)\HP Games\Chuzzle Deluxe\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files (x86)\HP Games\Diner Dash\Uninstall.exe" (start /wait "GS" "C:\Program Files (x86)\HP Games\Diner Dash\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files (x86)\HP Games\Dora's Carnival Adventure\Uninstall.exe" (start /wait "GS" "C:\Program Files (x86)\HP Games\Dora's Carnival Adventure\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files (x86)\HP Games\Family Feud 3\Uninstall.exe" (start /wait "GS" "C:\Program Files (x86)\HP Games\Family Feud 3\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files (x86)\HP Games\FATE\Uninstall.exe" (start /wait "GS" "C:\Program Files (x86)\HP Games\FATE\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files (x86)\HP Games\Jewel Quest Solitaire 2\Uninstall.exe" (start /wait "GS" "C:\Program Files (x86)\HP Games\Jewel Quest Solitaire 2\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files (x86)\HP Games\Mah Jong Medley\Uninstall.exe" (start /wait "GS" "C:\Program Files (x86)\HP Games\Mah Jong Medley\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files (x86)\HP Games\Monopoly\Uninstall.exe" (start /wait "GS" "C:\Program Files (x86)\HP Games\Monopoly\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files (x86)\HP Games\Mystery P.I. - The New York Fortune\Uninstall.exe" (start /wait "GS" "C:\Program Files (x86)\HP Games\Mystery P.I. - The New York Fortune\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files (x86)\HP Games\Peggle Nights\Uninstall.exe" (start /wait "GS" "C:\Program Files (x86)\HP Games\Peggle Nights\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files (x86)\HP Games\Penguins!\Uninstall.exe" (start /wait "GS" "C:\Program Files (x86)\HP Games\Penguins!\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files (x86)\HP Games\Plants vs. Zombies\Uninstall.exe" (start /wait "GS" "C:\Program Files (x86)\HP Games\Plants vs. Zombies\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files (x86)\HP Games\Poker Superstars III\Uninstall.exe" (start /wait "GS" "C:\Program Files (x86)\HP Games\Poker Superstars III\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files (x86)\HP Games\Polar Bowler\Uninstall.exe" (start /wait "GS" "C:\Program Files (x86)\HP Games\Polar Bowler\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files (x86)\HP Games\Polar Golfer\Uninstall.exe" (start /wait "GS" "C:\Program Files (x86)\HP Games\Polar Golfer\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files (x86)\HP Games\Scrabble\Uninstall.exe" (start /wait "GS" "C:\Program Files (x86)\HP Games\Scrabble\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files (x86)\HP Games\THE GAME OF LIFE\Uninstall.exe" (start /wait "GS" "C:\Program Files (x86)\HP Games\THE GAME OF LIFE\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files (x86)\HP Games\Totem Tribe\Uninstall.exe" (start /wait "GS" "C:\Program Files (x86)\HP Games\Totem Tribe\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files (x86)\HP Games\Virtual Families\Uninstall.exe" (start /wait "GS" "C:\Program Files (x86)\HP Games\Virtual Families\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files (x86)\HP Games\Virtual Villagers - The Secret City\Uninstall.exe" (start /wait "GS" "C:\Program Files (x86)\HP Games\Virtual Villagers - The Secret City\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files (x86)\HP Games\Wheel of Fortune 2\Uninstall.exe" (start /wait "GS" "C:\Program Files (x86)\HP Games\Wheel of Fortune 2\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files (x86)\HP Games\Yahtzee\Uninstall.exe" (start /wait "GS" "C:\Program Files (x86)\HP Games\Yahtzee\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files (x86)\HP Games\Zuma Deluxe\Uninstall.exe" (start /wait "GS" "C:\Program Files (x86)\HP Games\Zuma Deluxe\Uninstall.exe" >nul 2>&1)
REM HP Games legacy uninstaller: Spring 2010, Regions affected: Poland, Finland, United Kingdom, Canada, Italy, Germany, Japan, France, Korea, Spain, Switzerland, Netherlands, Belgium, Norway
if exist "C:\Program Files (x86)\HP Games\Bejeweled 2 Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Bejeweled 2 Deluxe\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Blasterball 3\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Blasterball 3\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Chuzzle Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Chuzzle Deluxe\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Diner Dash\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Diner Dash\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Dora's Carnival Adventure\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Dora's Carnival Adventure\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Farm Frenzy\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Farm Frenzy\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\FATE\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\FATE\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Jewel Quest Solitaire 2\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Jewel Quest Solitaire 2\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Mah Jong Medley\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Mah Jong Medley\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Peggle\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Peggle\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Polar Bowler\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Polar Bowler\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Polar Golfer\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Polar Golfer\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Slingo Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Slingo Deluxe\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\StoneLoops of Jurassica\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\StoneLoops of Jurassica\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Super Collapse 3\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Super Collapse 3\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\THE GAME OF LIFE\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\THE GAME OF LIFE\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Virtual Families\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Virtual Families\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Virtual Villagers - The Secret City\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Virtual Villagers - The Secret City\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\World of Goo\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\World of Goo\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Yahtzee\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Yahtzee\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\HP Games\Zuma Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\HP Games\Zuma Deluxe\Uninstall.exe" >nul 2>&1 )
REM HP Games legacy uninstaller: Summer 2009, Regions affected: Poland, Finland, United Kingdom, Italy, Germany, France, Spain, Switzerland, Netherlands, Belgium, Norway
if exist "C:\Program Files\HP Games\Agatha Christie - Death on the Nile\Uninstall.exe" (start /wait "GS" "C:\Program Files\HP Games\Agatha Christie - Death on the Nile\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files\HP Games\Bejeweled 2 Deluxe\Uninstall.exe" (start /wait "GS" "C:\Program Files\HP Games\Bejeweled 2 Deluxe\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files\HP Games\Bejeweled Twist\Uninstall.exe" (start /wait "GS" "C:\Program Files\HP Games\Bejeweled Twist\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files\HP Games\Blasterball 3\Uninstall.exe" (start /wait "GS" "C:\Program Files\HP Games\Blasterball 3\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files\HP Games\Build-a-lot 2\Uninstall.exe" (start /wait "GS" "C:\Program Files\HP Games\Build-a-lot 2\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files\HP Games\Cake Mania\Uninstall.exe" (start /wait "GS" "C:\Program Files\HP Games\Cake Mania\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files\HP Games\Chocolatier\Uninstall.exe" (start /wait "GS" "C:\Program Files\HP Games\Chocolatier\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files\HP Games\Chuzzle Deluxe\Uninstall.exe" (start /wait "GS" "C:\Program Files\HP Games\Chuzzle Deluxe\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files\HP Games\Diner Dash 2 Restaurant Rescue\Uninstall.exe" (start /wait "GS" "C:\Program Files\HP Games\Diner Dash 2 Restaurant Rescue\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files\HP Games\Diner Dash Hometown Hero\Uninstall.exe" (start /wait "GS" "C:\Program Files\HP Games\Diner Dash Hometown Hero\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files\HP Games\Diner Dash\Uninstall.exe" (start /wait "GS" "C:\Program Files\HP Games\Diner Dash\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files\HP Games\Farm Frenzy\Uninstall.exe" (start /wait "GS" "C:\Program Files\HP Games\Farm Frenzy\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files\HP Games\FATE\Uninstall.exe" (start /wait "GS" "C:\Program Files\HP Games\FATE\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files\HP Games\Insaniquarium Deluxe\Uninstall.exe" (start /wait "GS" "C:\Program Files\HP Games\Insaniquarium Deluxe\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files\HP Games\Magic Academy\Uninstall.exe" (start /wait "GS" "C:\Program Files\HP Games\Magic Academy\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files\HP Games\Mah Jong Quest\Uninstall.exe" (start /wait "GS" "C:\Program Files\HP Games\Mah Jong Quest\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files\HP Games\Mahjongg Artifacts\Uninstall.exe" (start /wait "GS" "C:\Program Files\HP Games\Mahjongg Artifacts\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files\HP Games\Mystery P.I. - The Lottery Ticket\Uninstall.exe" (start /wait "GS" "C:\Program Files\HP Games\Mystery P.I. - The Lottery Ticket\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files\HP Games\Peggle\Uninstall.exe" (start /wait "GS" "C:\Program Files\HP Games\Peggle\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files\HP Games\Polar Bowler\Uninstall.exe" (start /wait "GS" "C:\Program Files\HP Games\Polar Bowler\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files\HP Games\Polar Golfer\Uninstall.exe" (start /wait "GS" "C:\Program Files\HP Games\Polar Golfer\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files\HP Games\Polar Pool\Uninstall.exe" (start /wait "GS" "C:\Program Files\HP Games\Polar Pool\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files\HP Games\Slingo Deluxe\Uninstall.exe" (start /wait "GS" "C:\Program Files\HP Games\Slingo Deluxe\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files\HP Games\StoneLoops of Jurassica\Uninstall.exe" (start /wait "GS" "C:\Program Files\HP Games\StoneLoops of Jurassica\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files\HP Games\Sudoku Quest\Uninstall.exe" (start /wait "GS" "C:\Program Files\HP Games\Sudoku Quest\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files\HP Games\The Ancient Quest of Saqqarah\Uninstall.exe" (start /wait "GS" "C:\Program Files\HP Games\The Ancient Quest of Saqqarah\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files\HP Games\The Treasures of Montezuma\Uninstall.exe" (start /wait "GS" "C:\Program Files\HP Games\The Treasures of Montezuma\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files\HP Games\Turbo Pizza\Uninstall.exe" (start /wait "GS" "C:\Program Files\HP Games\Turbo Pizza\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files\HP Games\Virtual Villagers - The Secret City\Uninstall.exe" (start /wait "GS" "C:\Program Files\HP Games\Virtual Villagers - The Secret City\Uninstall.exe" >nul 2>&1)
if exist "C:\Program Files\HP Games\Zuma Deluxe\Uninstall.exe" (start /wait "GS" "C:\Program Files\HP Games\Zuma Deluxe\Uninstall.exe" >nul 2>&1)
REM HP Games legacy uninstaller: Summer 2009, Regions affected: USA, Canada
if exist "C:\Program Files\HP Games\18 Wheels of Steel - American Long Haul\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\18 Wheels of Steel - American Long Haul\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\4 Elements\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\4 Elements\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\7 Wonders - Treasures of Seven\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\7 Wonders - Treasures of Seven\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Amazing Adventures Around the World\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Amazing Adventures Around the World\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Bejeweled 2 Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Bejeweled 2 Deluxe\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Bejeweled Twist\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Bejeweled Twist\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Blackhawk Striker 2\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Blackhawk Striker 2\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Blasterball 3\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Blasterball 3\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Build-a-lot 2\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Build-a-lot 2\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Bus Driver\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Bus Driver\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Cake Mania 3\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Cake Mania 3\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Chuzzle Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Chuzzle Deluxe\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Crystal Maze\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Crystal Maze\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Diner Dash - Flo Through Time\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Diner Dash - Flo Through Time\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Diner Dash Hometown Hero\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Diner Dash Hometown Hero\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Dream Chronicles 2\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Dream Chronicles 2\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Farm Frenzy 2\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Farm Frenzy 2\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Farm Mania\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Farm Mania\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\FATE Undiscovered Realms\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\FATE Undiscovered Realms\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\FATE\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\FATE\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Final Drive Nitro\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Final Drive Nitro\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Jewel Quest 3\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Jewel Quest 3\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Jewel Quest Solitaire 2\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Jewel Quest Solitaire 2\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\LUXOR - Quest for the Afterlife\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\LUXOR - Quest for the Afterlife\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Mah Jong Quest\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Mah Jong Quest\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Mahjongg Artifacts\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Mahjongg Artifacts\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Mystery P.I. - The Lottery Ticket\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Mystery P.I. - The Lottery Ticket\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Mystery P.I. - The Vegas Heist\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Mystery P.I. - The Vegas Heist\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Peggle Nights\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Peggle Nights\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Peggle\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Peggle\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Penguins!\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Penguins!\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Poker Superstars III\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Poker Superstars III\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Polar Bowler\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Polar Bowler\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Polar Golfer\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Polar Golfer\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Polar Pool\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Polar Pool\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Slingo Supreme\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Slingo Supreme\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\The Hidden Object Game Show\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\The Hidden Object Game Show\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\The Hidden Object Show - Season 2\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\The Hidden Object Show - Season 2\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\The Price is Right\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\The Price is Right\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Tradewinds - Caravans\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Tradewinds - Caravans\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Virtual Villagers - A New Home\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Virtual Villagers - A New Home\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Virtual Villagers - The Secret City\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Virtual Villagers - The Secret City\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Wheel of Fortune 2\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Wheel of Fortune 2\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\World of Goo\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\World of Goo\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Zuma Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Zuma Deluxe\Uninstall.exe" >nul 2>&1 )
REM HP Games legacy uninstaller: Spring 2008, Regions affected: USA, Canada, France, United Kingdom, Germany, Italy, Spain, Korea, China, Hong Kong, Taiwan, Brazil
if exist "C:\Program Files\HP Games\3D Ultra Minigolf Adventures\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\3D Ultra Minigolf Adventures\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\5 Card Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\5 Card Deluxe\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\7 Wonders of the Ancient World\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\7 Wonders of the Ancient World\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Bejeweled 2 Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Bejeweled 2 Deluxe\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Blasterball 2 Revolution\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Blasterball 2 Revolution\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Blasterball 3\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Blasterball 3\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Bricks of Egypt\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Bricks of Egypt\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Chicken Invaders 3 - Revenge of the Yolk\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Chicken Invaders 3 - Revenge of the Yolk\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Chuzzle Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Chuzzle Deluxe\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Crystal Maze\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Crystal Maze\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Digby's Donuts\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Digby's Donuts\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Diner Dash 2 Restaurant Rescue\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Diner Dash 2 Restaurant Rescue\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Diner Dash\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Diner Dash\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\FATE\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\FATE\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Final Drive Nitro\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Final Drive Nitro\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Fish Tycoon\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Fish Tycoon\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Gem Shop\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Gem Shop\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Insaniquarium Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Insaniquarium Deluxe\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Jewel Quest Solitaire\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Jewel Quest Solitaire\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Jewel Quest\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Jewel Quest\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Jewels of Cleopatra\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Jewels of Cleopatra\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Magic Academy\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Magic Academy\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Mah Jong Quest\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Mah Jong Quest\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\My HP Game Console\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\My HP Game Console\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Ocean Express\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Ocean Express\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Otto's Magic Blocks\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Otto's Magic Blocks\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Overball\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Overball\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Peggle\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Peggle\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Penguins!\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Penguins!\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Polar Bowler\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Polar Bowler\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Polar Golfer Pineapple Cup\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Polar Golfer Pineapple Cup\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Polar Golfer\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Polar Golfer\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Puzzle Express\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Puzzle Express\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Rainbow Mystery\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Rainbow Mystery\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Rainbow Web\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Rainbow Web\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Ricochet Lost Worlds\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Ricochet Lost Worlds\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Shooting Stars Pool\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Shooting Stars Pool\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Slingo Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Slingo Deluxe\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Sudoku Quest\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Sudoku Quest\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Super Granny\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Super Granny\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Tradewinds\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Tradewinds\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Treasure Island\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Treasure Island\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Trijinx\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Trijinx\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Virtual Villagers - A New Home\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Virtual Villagers - A New Home\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Virtual Villagers - Chapter 2 - The Lost Children\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Virtual Villagers - Chapter 2 - The Lost Children\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Zuma Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Zuma Deluxe\Uninstall.exe" >nul 2>&1 )
rem HP Games legacy uninstaller: Spring 2009, Regions affected: France
if exist "C:\Program Files\HP Games\5 Card Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\5 Card Deluxe\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Agatha Christie - Death on the Nile\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Agatha Christie - Death on the Nile\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Age of Castles\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Age of Castles\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Bejeweled 2 Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Bejeweled 2 Deluxe\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Blasterball 3\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Blasterball 3\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Build-a-lot 2\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Build-a-lot 2\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Cake Mania\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Cake Mania\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Chuzzle Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Chuzzle Deluxe\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Diner Dash 2 Restaurant Rescue\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Diner Dash 2 Restaurant Rescue\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Diner Dash\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Diner Dash\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\FATE\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\FATE\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Fish Tycoon\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Fish Tycoon\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Gem Shop\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Gem Shop\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Granny in Paradise\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Granny in Paradise\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Insaniquarium Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Insaniquarium Deluxe\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Mah Jong Quest\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Mah Jong Quest\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Mahjongg Artifacts\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Mahjongg Artifacts\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Ocean Express\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Ocean Express\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Peggle\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Peggle\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Polar Bowler\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Polar Bowler\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Polar Golfer\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Polar Golfer\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Polar Pool\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Polar Pool\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Puzzle Express\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Puzzle Express\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Slingo Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Slingo Deluxe\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\SPORE Creature Creator Trial Edition\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\SPORE Creature Creator Trial Edition\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Sudoku Quest\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Sudoku Quest\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\The Treasures of Montezuma\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\The Treasures of Montezuma\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Tradewinds\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Tradewinds\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Virtual Villagers - The Secret City\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Virtual Villagers - The Secret City\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Zuma Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Zuma Deluxe\Uninstall.exe" >nul 2>&1 )
rem HP Games legacy Uninstaller: Fall 2008, Regions affected: Finland, United Kingdom, Italy, Germany, France, Spain, Switzerland, Netherlands, Belgium, Norway
if exist "C:\Program Files\HP Games\7 Wonders of the Ancient World\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\7 Wonders of the Ancient World\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Arctic Quest 2\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Arctic Quest 2\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Bejeweled 2 Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Bejeweled 2 Deluxe\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Blasterball 2 Revolution\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Blasterball 2 Revolution\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Blasterball 3\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Blasterball 3\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Build-a-lot\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Build-a-lot\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Chuzzle Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Chuzzle Deluxe\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Crystal Maze\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Crystal Maze\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Diner Dash 2 Restaurant Rescue\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Diner Dash 2 Restaurant Rescue\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Diner Dash\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Diner Dash\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\FATE\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\FATE\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Fish Tycoon\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Fish Tycoon\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Insaniquarium Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Insaniquarium Deluxe\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Jewel Quest Solitaire\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Jewel Quest Solitaire\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Jewel Quest\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Jewel Quest\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Magic Academy\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Magic Academy\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Mah Jong Adventures\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Mah Jong Adventures\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Mah Jong Quest\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Mah Jong Quest\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Ocean Express\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Ocean Express\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Peggle\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Peggle\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Penguins!\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Penguins!\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Polar Bowler\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Polar Bowler\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Polar Golfer\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Polar Golfer\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Ricochet Lost Worlds\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Ricochet Lost Worlds\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\SPORE Creature Creator Trial Edition\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\SPORE Creature Creator Trial Edition\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Super Granny\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Super Granny\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\The Treasures of Montezuma\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\The Treasures of Montezuma\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Tradewinds\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Tradewinds\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Virtual Villagers - A New Home\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Virtual Villagers - A New Home\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Virtual Villagers - Chapter 2 - The Lost Children\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Virtual Villagers - Chapter 2 - The Lost Children\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Zuma Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Zuma Deluxe\Uninstall.exe" >nul 2>&1 )
REM HP Games legacy uninstaller: Spring 2009, Regions affected: Poland, Finland, United Kingdom, Italy, Germany, France, Spain, Switzerland, Netherlands, Belgium, Norway,
if exist "C:\Program Files\HP Games\Agatha Christie - Death on the Nile\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Agatha Christie - Death on the Nile\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Bejeweled 2 Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Bejeweled 2 Deluxe\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Blasterball 3\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Blasterball 3\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Build-a-lot 2\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Build-a-lot 2\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Chuzzle Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Chuzzle Deluxe\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Crystal Maze\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Crystal Maze\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Diner Dash 2 Restaurant Rescue\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Diner Dash 2 Restaurant Rescue\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Diner Dash\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Diner Dash\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Escape the Museum\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Escape the Museum\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\FATE\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\FATE\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Gem Shop\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Gem Shop\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Granny in Paradise\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Granny in Paradise\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Insaniquarium Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Insaniquarium Deluxe\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Magic Academy\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Magic Academy\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Mah Jong Quest\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Mah Jong Quest\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Mahjongg Artifacts\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Mahjongg Artifacts\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Peggle\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Peggle\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Penguins!\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Penguins!\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Polar Bowler\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Polar Bowler\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Polar Golfer Pineapple Cup\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Polar Golfer Pineapple Cup\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Polar Golfer\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Polar Golfer\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Polar Pool\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Polar Pool\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Slingo Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Slingo Deluxe\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Snowy - Treasure Hunter 2\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Snowy - Treasure Hunter 2\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\SPORE Creature Creator Trial Edition\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\SPORE Creature Creator Trial Edition\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Tradewinds Legends\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Tradewinds Legends\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Tradewinds\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Tradewinds\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Virtual Villagers - A New Home\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Virtual Villagers - A New Home\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Virtual Villagers - The Secret City\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Virtual Villagers - The Secret City\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files\HP Games\Zuma Deluxe\Uninstall.exe" ( start /wait "GS" "C:\Program Files\HP Games\Zuma Deluxe\Uninstall.exe" >nul 2>&1 )

rem Packard Bell preloaded games
if exist "C:\Program Files (x86)\Packard Bell Games\Agatha Christie - Death on the Nile\Uninstall\Uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\Packard Bell Games\Agatha Christie - Death on the Nile\Uninstall\Uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\Packard Bell Games\Bejeweled 2 Deluxe\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\Packard Bell Games\Bejeweled 2 Deluxe\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\Packard Bell Games\Bejeweled 3\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\Packard Bell Games\Bejeweled 3\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\Packard Bell Games\Build-a-lot 4 - Power Source\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\Packard Bell Games\Build-a-lot 4 - Power Source\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\Packard Bell Games\Chronicles of Albian\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\Packard Bell Games\Chronicles of Albian\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\Packard Bell Games\Chuzzle Deluxe\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\Packard Bell Games\Chuzzle Deluxe\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\Packard Bell Games\Cradle of Rome 2\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\Packard Bell Games\Cradle of Rome 2\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\Packard Bell Games\Doras World Adventure\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\Packard Bell Games\Doras World Adventure\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\Packard Bell Games\FATE\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\Packard Bell Games\Chronicles of Albian\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\Packard Bell Games\Final Drive Nitro\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\Packard Bell Games\Final Drive Nitro\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\Packard Bell Games\Governor of Poker 2 Premium Edition\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\Packard Bell Games\Governor of Poker 2 Premium Edition\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\Packard Bell Games\FATE\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\Packard Bell Games\Chronicles of Albian\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\Packard Bell Games\Insaniquarium Deluxe\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\Packard Bell Games\Insaniquarium Deluxe\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\Packard Bell Games\Mystery of Mortlake Mansion\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\Packard Bell Games\Mystery of Mortlake Mansion\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\Packard Bell Games\Penguins!\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\Packard Bell Games\Penguins!\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\Packard Bell Games\Plants vs Zombies - Game of the Year\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\Packard Bell Games\Plants vs Zombies - Game of the Year\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\Packard Bell Games\Polar Bowler\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\Packard Bell Games\Polar Bowler\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\Packard Bell Games\Polar Golfer\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\Packard Bell Games\Polar Golfer\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\Packard Bell Games\Skip-Bo - Castaway Caper\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\Packard Bell Games\Skip-Bo - Castaway Caper\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\Packard Bell Games\Slingo Deluxe\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\Packard Bell Games\Slingo Deluxe\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\Packard Bell Games\Tradewinds Legends\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\Packard Bell Games\Tradewinds Legends\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\Packard Bell Games\Torchlight\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\Packard Bell Games\Torchlight\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\Packard Bell Games\Virtual Villagers 4 - The Tree of Life\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\Packard Bell Games\Virtual Villagers 4 - The Tree of Life\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\Packard Bell Games\Virtual Villagers 5 - New Believers\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\Packard Bell Games\Virtual Villagers 5 - New Believers\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\Packard Bell Games\Wedding Dash\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\Packard Bell Games\Wedding Dash\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\Packard Bell Games\Zuma Deluxe\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\Packard Bell Games\Zuma Deluxe\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\Packard Bell Games\Zumas Revenge\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\Packard Bell Games\Zumas Revenge\uninstall\uninstaller.exe" >nul 2>&1 )
rem the WildGames games
if exist "C:\Program Files (x86)\WildGames\4 Elements II\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\4 Elements II\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Agatha Christie - Death on the Nile\Uninstall\Uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Agatha Christie - Death on the Nile\Uninstall\Uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Airport Mania\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Airport Mania\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Aloha TriPeaks\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Aloha TriPeaks\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Azkend 2 The World Beneath\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Azkend 2 The World Beneath\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Barn Yarn Collectors Edition\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Barn Yarn Collectors Edition\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Bejeweled 2 Deluxe\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Bejeweled 2 Deluxe\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Bejeweled 3\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Bejeweled 3\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Bounce Symphony\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Bounce Symphony\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Build-a-lot Mysteries\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Build-a-lot Mysteries\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Build-a-lot\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Build-a-lot\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Building the Great Wall of China Collectors Edition\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Building the Great Wall of China Collectors Edition\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Cradle Of Egypt Collectors Edition\Uninstall\Uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Cradle Of Egypt Collectors Edition\Uninstall\Uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Cradle of Rome 2\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Cradle of Rome 2\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Crazy Chicken Soccer\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Crazy Chicken Soccer\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Curse at Twilight\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Curse at Twilight\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Delicious - Emilys Wonder Wedding Premium Edition\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Delicious - Emilys Wonder Wedding Premium Edition\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Delicious Emilys Childhood Memories Premium Edition\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Delicious Emilys Childhood Memories Premium Edition\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Delicious Emilys True Love Premium Edition\Uninstall\Uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Delicious Emilys True Love Premium Edition\Uninstall\Uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Doras World Adventure\Uninstall\Uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Doras World Adventure\Uninstall\Uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Empress of the Deep - The Darkest Secret\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Empress of the Deep - The Darkest Secret\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Farm Frenzy\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Farm Frenzy\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Farm to Fork Collectors Edition\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Farm to Fork Collectors Edition\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Farmington Tales 2 - Winter Crop\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Farmington Tales 2 - Winter Crop\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Fishdom 3 Collectors Edition\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Fishdom 3 Collectors Edition\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Fort Defense\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Fort Defense\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Game Explorer Categories - genres\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Game Explorer Categories - genres\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Governor of Poker 2 Premium Edition\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Governor of Poker 2 Premium Edition\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\House of 1000 Doors Family Secrets\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\House of 1000 Doors Family Secrets\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Island Tribe\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Island Tribe\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Jewel Match 3\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Jewel Match 3\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Jewel Quest Solitaire 2\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Jewel Quest Solitaire 2\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\John Deere Drive Green\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\John Deere Drive Green\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Joining Hands 2\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Joining Hands 2\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Jos Dream Organic Coffee 2\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Jos Dream Organic Coffee 2\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\King Oddball\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\King Oddball\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Letters from Nowhere 2\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Letters from Nowhere 2\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Lost in Reefs 2\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Lost in Reefs 2\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\LUXOR Evolved\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\LUXOR Evolved\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Magic Academy\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Magic Academy\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Magic Heroes Save Our Park\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Magic Heroes Save Our Park\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Mahjongg Artifacts\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Mahjongg Artifacts\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Mahjongg Dimensions Deluxe\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Mahjongg Dimensions Deluxe\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\My Kingdom for the Princess 3\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\My Kingdom for the Princess 3\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Mystery PI - Curious Case of Counterfeit Cove\Uninstall\Uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Mystery PI - Curious Case of Counterfeit Cove\Uninstall\Uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Peggle Nights\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Peggle Nights\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Penguins!\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Penguins!\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Plants vs Zombies - Game of the Year\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Plants vs Zombies - Game of the Year\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Polar Bowler 1st Frame\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Polar Bowler 1st Frame\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Polar Bowler\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Polar Bowler\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Polar Golfer\Uninstall\Uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Polar Golfer\Uninstall\Uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Ranch Rush 2 - Premium Edition\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Ranch Rush 2 - Premium Edition\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Roads of Rome 3\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Roads of Rome 3\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Rush Hour! Gas Station\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Rush Hour! Gas Station\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Sky High Farm\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Sky High Farm\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Solitaire Mystery Four Seasons\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Solitaire Mystery Four Seasons\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Sparkle 2\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Sparkle 2\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Tales of Lagoona\Uninstall\Uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Tales of Lagoona\Uninstall\Uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\The Chronicles of Emerland Solitaire\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\The Chronicles of Emerland Solitaire\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\The Treasures of Mystery Island The Ghost Ship\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\The Treasures of Mystery Island The Ghost Ship\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Trinklit Supreme\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Trinklit Supreme\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Vacation Quest - Australia\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Vacation Quest - Australia\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Viking Saga\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Viking Saga\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Virtual Families\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Virtual Families\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Virtual Villagers 4 - The Tree of Life\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Virtual Villagers 4 - The Tree of Life\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Virtual Villagers 5 - New Believers\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Virtual Villagers 5 - New Believers\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Wedding Dash\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Wedding Dash\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Youda Jewel Shop\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Youda Jewel Shop\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Zumas Revenge\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Zumas Revenge\uninstall\uninstaller.exe" >nul 2>&1 )if exist "C:\Program Files (x86)\WildTangent Games\Game Explorer Categories - casual\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Game Explorer Categories - casual\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Game Explorer Categories - enthusiast\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Game Explorer Categories - enthusiast\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Game Explorer Categories - family\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Game Explorer Categories - family\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Game Explorer Categories - genres\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Game Explorer Categories - genres\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Game Explorer Categories - kids\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Game Explorer Categories - kids\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Game Explorer Categories - main\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Game Explorer Categories - main\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Game Explorer Categories - touch\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Game Explorer Categories - touch\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Touchpoints\acer\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Touchpoints\acer\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Touchpoints\asus\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Touchpoints\asus\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Touchpoints\hp\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Touchpoints\hp\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Touchpoints\toshiba\uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Touchpoints\toshiba\uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Web Link - Command and Conquer Tiberium Alliances\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Web Link - Command and Conquer Tiberium Alliances\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Web Link - DoubleDown Casino\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Web Link - DoubleDown Casino\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Web Link - Dragons Of Atlantis\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Web Link - Dragons Of Atlantis\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Web Link - Sushi Cat\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Web Link - Sushi Cat\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Web Link - The Godfather 5 Families\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Web Link - The Godfather 5 Families\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Web Link - The Godfather Five Families\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Web Link - The Godfather Five Families\Uninstall.exe" >nul 2>&1 )
if exist "c:\program files (x86)\HP Games\Web Link - Club Penguin\Uninstall.exe" (start /wait "GS" "c:\program files (x86)\HP Games\Web Link - Club Penguin\Uninstall.exe" >nul 2>&1)
if exist "c:\program files (x86)\HP Games\Web Link - Dark Orbit\Uninstall.exe" (start /wait "GS" "c:\program files (x86)\HP Games\Web Link - Dark Orbit\Uninstall.exe" >nul 2>&1)
if exist "c:\program files (x86)\HP Games\Web Link - Habbo Hotel\Uninstall.exe" (start /wait "GS" "c:\program files (x86)\HP Games\Web Link - Habbo Hotel\Uninstall.exe" >nul 2>&1)
if exist "c:\program files (x86)\HP Games\Web Link - Seafight\Uninstall.exe" (start /wait "GS" "c:\program files (x86)\HP Games\Web Link - Seafight\Uninstall.exe" >nul 2>&1)
if exist "c:\program files (x86)\HP Games\Web Link - World of Warcraft\Uninstall.exe" (start /wait "GS" "c:\program files (x86)\HP Games\Web Link - World of Warcraft\Uninstall.exe" >nul 2>&1)
if exist "c:\program files (x86)\HP Games\Web Link - Polar Bowler Strike!\Uninstall.exe" (start /wait "GS" "c:\program files (x86)\HP Games\Web Link - Polar Bowler Strike!\Uninstall.exe" >nul 2>&1)
